### ISSUE TITLE
Allow to change the background color of the SettingsItem widget

### ISSUE THREAD

**Issue by Josee9988** [babstrap/babstrap_settings_screen#22]
I'm using version 0.1.5 and I can only modify the background color of the icon. But not the background color of the tile/card itself.

Even though I tried to use backgroundColor, but it seems to be pointless...

My code 

```dart
SettingsItem(
                  backgroundColor: Colors.red, // ignored
                  onTap: () {
                   ///
                  },
                  icons: Icons.foundation_outlined,
                  iconStyle: IconStyle(
                    backgroundColor: Colors.blueAccent,
                  ),
                  title: 'about_us'.tr(),
                  subtitle: 'meet_the_founders'.tr(),
                ),
```

**Comment by LordMaddhi** [comment]
+1 

please add this!

**Comment by vpulim** [comment]
I was able to change the card background color by setting `cardColor` in the ThemeData:

```
return MaterialApp(
  theme: ThemeData(
    ...
    cardColor: Colors.white,
  ),
```

**Comment by babstrap** [comment]
Hi everyone,
The 0.1.7 version is now available! You can now add backgroundColor on SettingGroup to customize it to your preference.

Thank you for your request, and I sorry for the late.

Best,

**Comment by babstrap** [comment]
Hi everyone,
The 0.1.7 version is now available! You can now add backgroundColor on SettingGroup to customize it to your preference.

Thank you for your request, and I sorry for the late.

Best,
